// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYD5gNyHbufRbNR4oCAf2l5U1kXKUyvTI',
    appId: '1:793340434521:web:0c57d52f384ce1a4acb948',
    messagingSenderId: '793340434521',
    projectId: 'watch-b5164',
    authDomain: 'watch-b5164.firebaseapp.com',
    storageBucket: 'watch-b5164.appspot.com',
    measurementId: 'G-1M4RJ471DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFZ_ex4tPKDWTYMYNZx4fodCp4I9FSqlI',
    appId: '1:793340434521:android:d482131f6e2f3c76acb948',
    messagingSenderId: '793340434521',
    projectId: 'watch-b5164',
    storageBucket: 'watch-b5164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIBoIZvZlVWbObac_iOJVO3TAl141rHz4',
    appId: '1:793340434521:ios:33e76b7bd9b7e7e9acb948',
    messagingSenderId: '793340434521',
    projectId: 'watch-b5164',
    storageBucket: 'watch-b5164.appspot.com',
    iosClientId: '793340434521-mhdf2gfcv8bqdh1tu7995vh7ibl148lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIBoIZvZlVWbObac_iOJVO3TAl141rHz4',
    appId: '1:793340434521:ios:33e76b7bd9b7e7e9acb948',
    messagingSenderId: '793340434521',
    projectId: 'watch-b5164',
    storageBucket: 'watch-b5164.appspot.com',
    iosClientId: '793340434521-mhdf2gfcv8bqdh1tu7995vh7ibl148lp.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchlist',
  );
}
